name: reqwest
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.3.4 <4.0.0'


dependencies:
  flutter:
    sdk: flutter

  intl: any
  flutter_gen: ^5.4.0
  cached_network_image: ^3.3.0
  file_picker: ^6.1.1
  image_picker: ^1.0.4
  flutter_bloc: ^8.1.6
  flutter_screenutil: ^5.9.3
  flutter_svg: ^2.0.10+1
  flutter_quick_router: ^0.0.3
  firebase_core: ^3.4.0
  firebase_auth: ^5.2.0
  cloud_firestore: ^5.4.0
  firebase_storage: ^12.2.0
  shimmer: ^3.0.0
  firebase_messaging: ^15.1.0
  flutter_local_notifications: ^18.0.1
  url_launcher: ^6.3.1
  
dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner:
  flutter_gen_runner:
  flutter_lints: ^3.0.0


flutter:
  uses-material-design: true
  
  assets: 
    - assets/icons/
    - assets/images/

  fonts:
    - family: Gilroy
      fonts:
        - asset: assets/fonts/Gilroy-Bold.ttf
          weight: 700
        - asset: assets/fonts/Gilroy-Medium.ttf
          weight: 500
        - asset: assets/fonts/Gilroy-Regular.ttf
          weight: 400
        - asset: assets/fonts/Gilroy-SemiBold.ttf
          weight: 600

